# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production --ignore-scripts

# Copy source code
COPY . .

ENV NODE_ENV=production

CMD ["node", "index.js"]
